version: "3.9"
services:
  pdf_service:
    build: ../pdf_service
    container_name: pdf_service
    ports:
      - "5002:5002"
    restart: unless-stopped

  webapp:
    build: ../webapp
    container_name: webapp
    ports:
      - "5001:5001"
    restart: unless-stopped
